/*
 * DO NOT EDIT THIS FILE. Generated by checkmk.
 * Edit the original source file "buffer.ts" instead.
 */

#include <check.h>

#line 1 "buffer.ts"
#include <setjmp.h>
#include <stdint.h>
#include "buf.h"

int aborted;
static jmp_buf escape;
int* buffer = 0;

START_TEST(init_capacity)
{
#line 11
	ck_assert_int_eq(buf_capacity(buffer), 0);
	ck_assert_int_eq(buf_size(buffer), 0);
	buf_push(buffer, 5);
	ck_assert_int_eq(buf_size(buffer), 1);
	ck_assert(buffer[0] == 5);
	buf_clear(buffer);
	ck_assert_int_eq(buf_size(buffer), 0);
	ck_assert_ptr_ne(buffer, 0);
	buf_free(buffer);
	ck_assert_ptr_eq(buffer, 0);

}
END_TEST

START_TEST(clear_null)
{
#line 23
	buf_clear(buffer);
	ck_assert_int_eq(buf_size(buffer), 0);
	ck_assert_ptr_eq(buffer, 0);

}
END_TEST

START_TEST(push_index_select)
{
#line 28
	long *ai = 0;
    for (int i = 0; i < 10000; i++)
        buf_push(ai, i);
	ck_assert_int_eq(buf_size(ai), 10000);
	int match = 0;
	for (int i = 0; i < (int)(buf_size(ai)); i++)
        match += ai[i] == i;
	ck_assert_int_eq(match, 10000);
	buf_free(ai);

}
END_TEST

START_TEST(grow_trunk)
{
#line 39
	long *ai = 0;
	buf_grow(ai, 1000);
	ck_assert_int_eq(buf_capacity(ai), 1000);
	ck_assert_int_eq(buf_size(ai), 0);
    buf_trunc(ai, 100);
	ck_assert_int_eq(buf_capacity(ai), 100);
    buf_free(ai);

}
END_TEST

START_TEST(pop)
{
#line 48
	buf_push(buffer, 1);
    buf_push(buffer, 2);
    buf_push(buffer, 3);
    buf_push(buffer, 4);
	ck_assert_int_eq(buf_size(buffer), 4);
    ck_assert_int_eq(buf_pop(buffer), 4);
    buf_trunc(buffer, 3);
	ck_assert_int_eq(buf_size(buffer), 3);
    ck_assert_int_eq(buf_pop(buffer), 3);
    ck_assert_int_eq(buf_pop(buffer), 2);
    ck_assert_int_eq(buf_pop(buffer), 1);
	ck_assert_int_eq(buf_size(buffer), 0);
    buf_free(buffer);	

}
END_TEST

int main(void)
{
    Suite *s1 = suite_create("Buffer");
    TCase *tc1_1 = tcase_create("Buffer");
    SRunner *sr = srunner_create(s1);
    int nf;

    suite_add_tcase(s1, tc1_1);
    tcase_add_test(tc1_1, init_capacity);
    tcase_add_test(tc1_1, clear_null);
    tcase_add_test(tc1_1, push_index_select);
    tcase_add_test(tc1_1, grow_trunk);
    tcase_add_test(tc1_1, pop);

    srunner_run_all(sr, CK_ENV);
    nf = srunner_ntests_failed(sr);
    srunner_free(sr);

    return nf == 0 ? 0 : 1;
}
